#
# Makefile for the led tfa9xxx driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_NUBIA_LED_TFA9XXX) += tfa2_container.o
obj-$(CONFIG_NUBIA_LED_TFA9XXX) += tfa2_dev.o
obj-$(CONFIG_NUBIA_LED_TFA9XXX) += tfa2_haptic.o
obj-$(CONFIG_NUBIA_LED_TFA9XXX) += tfa2_init.o
obj-$(CONFIG_NUBIA_LED_TFA9XXX) += tfa9xxx.o
obj-$(CONFIG_NUBIA_LED_TFA9XXX) += tfa9xxx_haptic.o

