#
# Makefile for the led driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_NUBIA_LED)		+= aw9106_led0/
obj-$(CONFIG_NUBIA_LED)		+= aw9106_led1/
obj-$(CONFIG_NUBIA_LED)		+= aw22xxx/
obj-$(CONFIG_NUBIA_LED)		+= tfa9xxx/

