#---------------------------RGB SENSOR----------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_RGB_BH1745)			+= rohm_bh1745.o
obj-$(CONFIG_NUBIA_VIRTUAL_PROXIMITY)           += virtual_proximity.o
#---------------------------HALL SENSOR---------------------------------#
obj-$(CONFIG_NUBIA_SENSORS_HALL_DEVICE)  		+= hall_device.o


obj-$(CONFIG_NUBIA_SENSORS_TMD3702)				+= tmd3702/

obj-$(CONFIG_NUBIA_SENSORS_PROX_PA224)			+= txc_pa224/

obj-$(CONFIG_NUBIA_DOUBLE_PROXIMITY)			+= double_proximity/
##-----------add tmd2725 for NX619J ----------#
obj-$(CONFIG_NUBIA_SENSORS_TMD2725)			+= tmd2725/